// antlabs, guonaihong 2023
package fromurl

import (
	"net/url"

	"github.com/antlabs/tostruct/internal/map2struct"
)

// TODO:
// 目前fromurl只会处理查询字符串, 把这一部分生成为结构体
// 对于路径部分, 会等到后面再处理, 假如有两个/hello/张三 /hello/李四 归纳出 /hello/:name 有点麻烦

type FromURL struct {
	structName string
	rawURL     string
}

// url直接从构造函数里面传递过来, 一般url不会太长, 不需要用流式解析
func New(rawURL string) *FromURL {
	return &FromURL{rawURL: rawURL}
}

// 设置默认值
func (u *FromURL) setStructDef() *FromURL {
	if u.structName == "" {
		u.structName = "Autogenerated"
	}
	return u
}

// 设置结构体的名字
func (u *FromURL) StructName(name string) *FromURL {
	u.structName = name
	return u
}

// 生成
func (u *FromURL) Gen() (string, error) {
	u.setStructDef()

	u2, err := url.Parse(u.rawURL)
	if err != nil {
		return "", err
	}

	return map2struct.MapGenStruct(map[string][]string(u2.Query()), u.structName, "form")
}
