// antlabs, guonaihong 2023
// apache 2.0
package url

import (
	"net/url"

	"github.com/antlabs/tostruct/internal/map2struct"
	"github.com/antlabs/tostruct/option"
)

type URL struct {
	structName string
	rawURL     string
}

func Marshal(rawURL string, opt ...option.Option) {

}

// url直接从构造函数里面传递过来, 一般url不会太长, 不需要用流式解析
func New(rawURL string) *URL {
	return &URL{rawURL: rawURL}
}

// 设置默认值
func (u *URL) setStructDef() *URL {
	if u.structName == "" {
		u.structName = "Autogenerated"
	}
	return u
}

// 设置结构体的名字
func (u *URL) StructName(name string) *URL {
	u.structName = name
	return u
}

// 生成
func (u *URL) Gen() (string, error) {
	u.setStructDef()

	u2, err := url.Parse(u.rawURL)
	if err != nil {
		return "", err
	}

	return map2struct.MapGenStruct(map[string][]string(u2.Query()), u.structName, "form")
}
